### ISSUE TITLE
Benchmarking and minor doc changes

### ISSUE THREAD

**Issue by jimvdl** [Ceikry/idx#1]
Hi, creator of [rs-cache](https://github.com/jimvdl/rs-cache) here o/

I recently stumbled upon your cache library and wanted to try and benchmark it against mine. What cache version are you using?

On another note; some minor things I noticed in your documentation:
- The reference linking to your `databuffer` crate is misspelled https://github.com/Ceikry/idx/blob/ebc40524284ee86064fbe598c7d30de2b4ac15c6/src/lib.rs#L15
- I think you meant created instead of creating?https://github.com/Ceikry/idx/blob/ebc40524284ee86064fbe598c7d30de2b4ac15c6/src/lib.rs#L96

I really like the lazy data loading on reads. Awesome crate overall, keep it up! :)

**Comment by Ceikry** [comment]
Thank you! Sorry, I just now saw this, I am quite busy these days. This crate is designed to read caches between the 200s and 600s, though there's probably some gaps in compatibility. I wish I had more time to put towards this but I'm just painfully preoccupied here lately.

**Comment by jimvdl** [comment]
No worries, it looks great so far! and I'm sure mine has gaps and missing features too. Do you still remember what version you used for your benchmark? This way I can try and benchmark from the same data sizes to not skew anything.

**Comment by Ceikry** [comment]
again, sorry for the terribly late response. I used an authentic 578 cache, the same one you can get on the OpenRS2 archives, december 2009 variant.

**Comment by jimvdl** [comment]
Not a problem at all, thank you very much! I'll report back to you if I find the time to run some benchmarks and if they yield some interesting results.

**Comment by jimvdl** [comment]
I've _finally_ found some spare time to run our benchmarks. I've cloned your project and ran the benchmark on my machine with the same cache that I'd downloaded to prevent skewing the results. I've downloaded the (December) 578 cache version from OpenRS2 archive.

`idx` benchmark results:
  | Lower bound | Estimate | Upper bound
-- | -- | -- | --
Slope | 1.1014 µs | 1.1444 µs | 1.1808 µs
R² | 0.4144214 | 0.4305802 | 0.4189423
Mean | 945.33 ns | 981.47 ns | 1.0186 µs
Std. Dev. | 165.39 ns | 186.75 ns | 204.45 ns
Median | 892.26 ns | 920.24 ns | 996.01 ns
MAD | 141.90 ns | 188.30 ns | 246.87 ns

1.1014 µs == 1101,4 ns

`rscache` benchmark results:
  | Lower bound | Estimate | Upper bound
-- | -- | -- | --
Slope | 383.57 ns | 384.53 ns | 385.53 ns
R² | 0.9835719 | 0.9844052 | 0.9834986
Mean | 383.07 ns | 383.81 ns | 384.65 ns
Std. Dev. | 2.7917 ns | 4.0378 ns | 5.3681 ns
Median | 382.04 ns | 382.65 ns | 383.49 ns
MAD | 1.8835 ns | 2.5377 ns | 3.3916 ns

The difference might be attributed to my use of [memmap2](https://crates.io/crates/memmap2). I use memory mapping because rs-cache also supports the RS3 cache format which is at least ~7gb and at most ~15gb last time I checked. Requesting data from such a large file needs to be performant. I've made a dedicated [`Dat2`](https://docs.rs/rune-fs/latest/runefs/struct.Dat2.html) type which interfaces with the memory mapped file. Memory mapping is _a bit_ unsafe though but should be fine while the cache remains in read-only mode and no other external processes mutate the cache data.

That said, your cache is still extremely fast, to a point where I doubt anyone would notice a difference when interchangeably using either on of ours. idx offers more flexibility out of the box whereas rs-cache is very limited in that regard because of its high-level simplicity, which makes them great competitors depending on what you're looking for.
